version: '2.4'
services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: ocppSmartHome
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  backend:
    image: org.ocpp.smart.home:1.0.0
    container_name: ocppSmartHome
    restart: on-failure
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
                  "spring.datasource.url": "jdbc:mysql://database:3306/ocppSmartHome"
                }'

  angular-service:
    container_name: angularContainer
    build: ../src/main/kotlin/org/ocpp/smart/home/frontend
    volumes:
      - '../src/main/kotlin/org/ocpp/smart/home/frontend:/usr/src/app'
    ports:
      - '4200:4200'

volumes:
  database: {}
